Add suggested command when 'exec' gets an unrecognized option
canonical/multipass pull request #1863
Opened 2020-11-29 06:16 UTC by dlbeck

Addresses #531 . When a user forgets to separate options with `--` when running the `exec` command, provides a suggested command that includes the `--`. Below is a screenshot of the behavior with the change.

![multipass_error_msg](https://user-images.githubusercontent.com/48418745/100534761-6f9e1b00-31e0-11eb-83c6-58aadcb041b3.png)

2020-11-30 10:23 UTC, Saviq commented
bors try

2020-11-30 12:19 UTC, ricab requested changes
Hi @dlbeck. Thanks again for your PR :slightly_smiling_face: I am requesting a few changes inline. I know that you followed the issue description closely, but we discussed a bit now and there are a couple of aspects that we think should be simplified. I will comment on the issue as well, for coherence.

2020-11-30 12:19 UTC, ricab commented on src/client/cli/argparser.cpp
> +            suggestedCommand.insert(3, "--");
Getting the right command in all cases would be quite tricky. A few examples of difficulties: 
  * the input could require the `--` to be in a different place (e.g. `multipass -vvv exec ...`)
  * bad options might be mistakes on genuine multipass options (e.g. `multipass exec --helpp`)
  * there could be more than one problem (e.g. `multipass --nonsense exec ls -la`)
  * If arguments had special characters, when printing the amended command back, we'd have to at least quote those

For these reasons, I think it's best to just say that the right usage is `multipass exec <instance> -- <command> <arguments>`.

2020-11-30 12:19 UTC, ricab commented on src/client/cli/argparser.cpp
> +            cerr << "\nYou need to separate the options to be passed to the command with \"--\", like this: \n";
I think we could use a nicer message. Something like: "Options to the inner command should come after \"--\", like this:"

2020-12-01 04:05 UTC, dlbeck commented
Thanks for the review @ricab . I have addressed those changes!

2020-12-02 11:09 UTC, ricab commented
bors try

2020-12-02 11:54 UTC, ricab commented
bors try-

2020-12-02 11:55 UTC, ricab commented
bors try

2020-12-02 12:11 UTC, ricab commented
grrr 

bors try

2020-12-02 15:14 UTC, ricab reviewed
Hi @dlbeck, The code looks good to me now, thanks. We're having some trouble with CI currently and I wasn't able to test yet, will do that later.

However, we do try to add only tested code as much as possible, so I would like to request that you add tests for the new functionality you add in this PR. That would involve some simple [tests for the `ArgParser`](https://github.com/canonical/multipass/blob/33a351d419f8f755fa222c68f85717e50ba3dbf3/tests/test_argparser.cpp#L57) and something checking the error msg [in the exec command](https://github.com/canonical/multipass/blob/0d1588c6ef197ea078fd48c095d27c5ca4840a48/tests/test_cli_client.cpp#L721). Here's an example of [how to check what you get in the cerr stream](https://github.com/canonical/multipass/blob/0d1588c6ef197ea078fd48c095d27c5ca4840a48/tests/test_cli_client.cpp#L588).

2020-12-02 15:31 UTC, ricab commented
Once again

bors try

2020-12-03 06:33 UTC, dlbeck commented
@ricab Thanks for pointing me in the right direction on testing. I have added 3 tests

1. If a command has an unknown option and doesn't contain `--`, the new error msg prints.
2. If a command has an unknown option and does contain `--`, the new error msg doesn't print.
3. If a command does not have any unknown options and does not contain `--`, the new error msg doesn't print

Right now, 1 passes but 2 and 3 fail. I'm pretty confident these fail because I don't use the testing framework correctly. Test 2 requires a `--` to be in the `send_command` . However,  I believe the `--` causes `send_command` to fail because when I remove it, the `send_command` failure in the screenshot below no longer occurs. Test 3 seems to fail because we don't pass in a correct "known" option.  When I tried passing in a known option like `--help`, I got the `send_command` error (see screenshot). This is interesting because when I use an unknown option, the `send_command` error no longer occurs.

Any advice you have on resolving these issues or properly using the exec testing framework would be appreciated. Thanks!
![image](https://user-images.githubusercontent.com/48418745/100971484-02062d80-3505-11eb-9e7c-d919c7c3d401.png)

2020-12-03 10:26 UTC, ricab reviewed
Hi @dlbeck, you're very close. Only a couple of simple changes and it should work.

2020-12-03 10:26 UTC, ricab commented on tests/test_cli_client.cpp
> +    EXPECT_THAT(send_command({"exec", "foo", "--", "cmd", "--unknownOption"}, trash_stream, cerr_stream),
Hey @dlbeck , this looks well structured, so Multipass wouldn't fail the command. I believe you want `--unknownOption` to come before `--`.

2020-12-03 10:26 UTC, ricab commented on tests/test_cli_client.cpp
> +                Eq(mp::ReturnCode::CommandLineError));
Here, `--help` is accepted as a request for help to the `exec` command, so it doesn't fail either. I think you want to expect a success in this case.

2020-12-03 16:56 UTC, ricab commented on tests/test_cli_client.cpp
> +        << "cerr has: " << cerr_stream.str();
Oh, one more thing. You can use a higher-level testing predicate, like this:

```c++
    EXPECT_THAT(cerr_stream.str(), HasSubstr("expected substr"));
```

It's simpler, more expressive, and leaves it to the testing framework to print the values that didn't match.

2020-12-04 03:48 UTC, dlbeck commented
Thanks @ricab! I modified the tests and they are all passing now.

2020-12-04 10:17 UTC, ricab commented
bors try

2020-12-04 11:20 UTC, ricab commented
bors retry

2020-12-05 18:16 UTC, dlbeck commented
@ricab Is there anything else that needs to be done on this PR before it's landed?

2020-12-07 15:05 UTC, ricab approved these changes
I finally tested and everything seems to work as it should. Code and tests look good. Thanks again @dlbeck 

bors r+

2020-12-07 16:47 UTC, Saviq commented
bors r=ricab

2020-12-07 17:49 UTC, merged