[cli] Fix launch client logging messages
canonical/multipass pull request #2055
Opened 2021-04-14 15:32 UTC by townsend2010

Create logger for thread and slot during the VM creation.
Let the client's streaming callback handle log message printing since different operations such as launch may handle this differently.
Modify AnimatedSpinner to save the current message and start again using the saved current message.

2021-04-23 14:00 UTC, Saviq requested changes
I wonder if we could make this part of the spinner?
```cpp
        if (!reply.log_line().empty())
        {
            spinner.stop();
            cerr << reply.log_line() << "\n";
            spinner.start();
        }
```

Like a:
```cpp
AnimatedSpinner::print(ostream stream, std::string message);
```

2021-04-23 14:08 UTC, townsend2010 commented
@Saviq,

> I wonder if we could make this part of the spinner?

Probably could do something like that.  I'll look into it.

2021-04-23 14:10 UTC, townsend2010 commented on tests/test_cli_client.cpp
> +        }));
Yeah, I think that would be cleaner.

2021-04-29 13:27 UTC, townsend2010 commented on tests/test_cli_client.cpp
> +        }));
Done

2021-04-29 13:28 UTC, townsend2010 commented
> I wonder if we could make this part of the spinner?

Ok, done :smiley:

2021-05-03 08:59 UTC, Saviq approved these changes
Yups!

bors merge

2021-05-03 10:12 UTC, merged