[ubuntu_image_host] Only reject multiple hash matches if not a full hash
canonical/multipass pull request #2085
Opened 2021-05-03 19:51 UTC by townsend2010

It's possible that the same full hash will exist in both the release and daily remotes, so don't reject it.

Fixes #2072

2021-05-17 13:39 UTC, Saviq requested changes
Any chance for a test?

2021-05-17 13:39 UTC, Saviq commented on src/daemon/ubuntu_image_host.cpp
> +    // If more than one match and query is a hash but not a full hash, throw an exception
```suggestion
    // If a partial hash query matches more than once, throw an exception
```

2021-05-17 14:05 UTC, townsend2010 commented
> Any chance for a test?

Yeah, probably should make a test specific for this case.

2021-05-17 18:48 UTC, townsend2010 commented
Ok, tests added to hopefully check the conditions this is fixing.

2021-05-21 14:40 UTC, Saviq approved these changes
Looks legit!

bors merge

2021-05-21 15:24 UTC, townsend2010 commented
bors retry

2021-05-21 16:20 UTC, townsend2010 commented
bors retry

2021-05-21 17:00 UTC, townsend2010 commented
Ok, I'm just going to wait until #2118 gets merged before trying this anymore.

2021-05-22 01:27 UTC, townsend2010 commented
bors retry

2021-05-22 02:57 UTC, merged