Issue #1118
canonical/multipass pull request #2099
Opened 2021-05-09 17:43 UTC by surahman

**_With respect to issue #1118:_**
Added a check on `DNSMasq` bootstrapping for `dnsmasq.hosts` file in the constructor. If absent, an empty file will be created in the `data_dir`.

2021-05-10 11:57 UTC, townsend2010 requested changes
Hi @surahman!

Thanks for this!  I have a couple of inline niggles and I would also like to ask you to add a test under `tests/qemu/test_dnsmasq_server.cpp` please.

2021-05-10 11:57 UTC, townsend2010 commented on src/platform/backends/qemu/dnsmasq_server.cpp
> +    QFile fd_Hosts(QDir(data_dir).filePath("dnsmasq.hosts"));
Could you change the variable name to `fd_hosts` instead to match the naming scheme of other variables?

2021-05-10 11:57 UTC, townsend2010 commented on src/platform/backends/qemu/dnsmasq_server.cpp
> +        fd_Hosts.close();
This `close()` isn't necessary as [`QFile`'s dtor](https://doc.qt.io/qt-5/qfile.html#dtor.QFile) will close it automatically, but it's not wrong to have it either.

2021-05-10 14:15 UTC, Saviq commented
Will reopen to kick the CLA check.

2021-05-10 16:03 UTC, surahman commented
@Saviq sorry about, privacy setting on Github were complaining about email address exposure before.

2021-05-10 18:41 UTC, Saviq commented
@surahman the `gitignore` commit still has the `-` email. But please remove that commit anyway :)

2021-05-10 19:16 UTC, Saviq commented
> @Saviq sorry I thought I already had - I just filled it out again.

Thanks, maybe it didn't go through our legal wheels… Now I know you did, I'll follow up our side.

Thanks a bunch, again, for your help!

2021-05-17 12:18 UTC, townsend2010 commented
bors try

2021-05-17 13:07 UTC, townsend2010 commented
Ok, all we're missing a simple little test to ensure the `dnsmasq.hosts` file does indeed exist.  I see the codecov reports the line being covered, but I think an explicit test would be beneficial.

2021-05-17 16:05 UTC, surahman commented
I have added a quick test. Is there anything I need to do to fix the CI issue?
`mkdir: cannot create directory '/etc/systemd/system': File exists`

2021-05-17 16:07 UTC, townsend2010 commented
Thanks!
> Is there anything I need to do to fix the CI issue?

I'll for this CI run to complete and then look at the error, if there is one.

2021-05-17 16:41 UTC, townsend2010 commented
Looks like CI passed fine with your added test.  I'm not sure where you saw that failure before though.

2021-05-17 16:45 UTC, townsend2010 approved these changes
Ok, this looks good.  Thanks!

bors merge

2021-05-17 21:28 UTC, Saviq commented
Sorry @surahman, we're having some reliability issues with a couple tests in CI…

bors retry

2021-05-17 22:02 UTC, surahman commented
@Saviq no worries, it is interesting to see the workflow :)

2021-05-18 08:22 UTC, Saviq commented
bors retry

2021-05-18 10:38 UTC, merged