sshfs infinitely looping on missing mount directory
canonical/multipass pull request #2718
Opened 2022-08-24 21:58 UTC by sharder996

This PR add a check to make sure that the given directory exists before attempting to mount it. If the directory is not found, the host and target directories will be removed from the database.

Fixes #1677

2022-08-24 22:03 UTC, sharder996 commented
While a `warning` level log message is recorded on a mount being removed, the cli does not display anything. Since the current state of `main` only allows for passing back errors (resulting in a message of `start failed` which is inappropriate since the command still works) I am putting up what I have so far so that we can discuss how we might want to go about displaying warnings as well.

2022-09-02 13:50 UTC, andrei-toterman commented
Hi @sharder996! Nice work, and it indeed seems to function properly. But I got one proposal, open for debate: What if we don't remove the mount entry if it failed? We can check if the directory exists, and if it doesn't, just report it to the user and skip its mounting, but leave the mount entry there, just in case the directory reappears back, so the user doesn't have to mount it again. Opinions?

2022-09-02 16:06 UTC, sharder996 commented
Hello @andrei-toterman I think we should remove mount entries if an exception occurs while mounting them. Not removing them, invalid mounts would be displayed with valid mounts in `multipass info <instance>` with nothing differentiating them. Also, if the user broke a mount by deleting/moving a source directory, I think it should be expected that they have to re-mount the directory.

But, I think the decision of what we should do here basically boils down to the question of "Do we want to try to fix the user's problem for them or have them fix it themselves?".

2022-09-02 16:11 UTC, townsend2010 commented
Hey @sharder996 and @andrei-toterman,

> Do we want to try to fix the user's problem for them or have them fix it themselves?

If a directory is missing on the host, I believe the user should have to fix it since it's most likely removed intentionally.  I also think we should treat it as a failure and not leave the mount defined.  The user must either fix the issue or just not have the particular mount defined.  My 2 cents :slightly_smiling_face:

2022-09-05 11:31 UTC, andrei-toterman requested changes

2022-09-05 11:31 UTC, andrei-toterman commented on src/daemon/daemon.cpp
> +                reply.set_log_line(fmt::to_string(warnings));
this is calling `fmt::to_string` twice, which involves two string allocations. you could use `warnings.size() > 0` instead

2022-09-05 11:31 UTC, andrei-toterman commented on src/sshfs_mount/sshfs_mounts.cpp
> +        throw std::runtime_error(fmt::format("Mount path `{}` does not exist.", source_path));
i see that you're using backticks here, but in most other places single quotes are used for printing paths

2022-09-05 11:31 UTC, andrei-toterman commented on src/daemon/daemon.cpp
> +                                   fmt::format("Removing mount \'{}\' from {}: {}\n", target_path, name, e.what()));
i don't think single quotes need to be escaped like that, they should be printed just fine without the backslash

2022-09-05 11:31 UTC, andrei-toterman commented on src/client/cli/cmd/restart.cpp
> +    };
i see there are some similar lines in `start.cpp` and they are covered. could these be covered in the same way?

2022-09-06 11:27 UTC, andrei-toterman commented
Alright, looks good to me! The code that still remains uncovered is pretty much in sections that were already uncovered, so I guess it is okay!

bors merge

2022-09-06 11:28 UTC, andrei-toterman approved these changes

2022-09-06 11:30 UTC, andrei-toterman approved these changes
Alright, looks good to me! The code that still remains uncovered is pretty much in sections that were already uncovered, so I guess it is okay!

bors merge

2022-09-06 13:12 UTC, townsend2010 commented
bors retry

2022-09-06 14:39 UTC, townsend2010 commented
One more time...

bors retry

2022-09-06 17:44 UTC, townsend2010 commented
Hmm, bors keeps failing on the same test on Windows with this PR.  Something fishy is going on, but it needs to be investigated before we merge.

2022-09-06 17:46 UTC, townsend2010 commented
The test is `Client/TimeoutSuite.command_exits_on_timeout/2, where GetParam() = "restart"` and this code touches the `restart` handling.  It may be introducing a race on Windows since it's a slow VM.

2022-09-07 13:58 UTC, sharder996 commented
@townsend2010 The first time bors failed, it failed on `where GetParam() = "start"` which was unmodified. Indication that this test failure is unrelated? I took a look at the `restart` test in question (which comes from the same test suite), but I'm not seeing anything to suggest why it's failing.

2022-09-07 20:43 UTC, merged