[gui] not reacting to primary instance being purged
canonical/multipass pull request #2732
Opened 2022-08-31 19:50 UTC by sharder996

This PR fixes the text shown in the gui when no primary instance is found.

Fixes #1241

2022-09-05 13:14 UTC, andrei-toterman requested changes

2022-09-05 13:14 UTC, andrei-toterman commented on src/client/gui/gui_cmd.cpp
> +        petenv_shell_action.setEnabled(false);
i think this should remain `true`. so far, if there was no primary instance, clicking that button would launch a terminal and create the primary instance, and that's a nice one-click action that would put you into the shell of the primary instance

2022-09-05 13:14 UTC, andrei-toterman commented on src/client/gui/gui_cmd.cpp
> +        }
i know this is purely a matter of preference in this case, but i think an early `return` is better than an `else` + it doesn't really change any functionality, it's just a style thing. but i also get the appeal in this simple case, so you can leave it like this if you like it :smiley:

2022-09-06 14:23 UTC, andrei-toterman approved these changes
Perfect!

bors merge

2022-09-06 16:07 UTC, townsend2010 commented
Seems a race in the Windows tests is starting to show up.  We'll try it once more...

bors retry

2022-09-06 20:22 UTC, merged