fixed the false time error where user specifies the new instance name
canonical/multipass pull request #2955
Opened 2023-03-09 09:07 UTC by georgeliao

2023-03-09 20:48 UTC, townsend2010 requested changes
Hey @georgeliao!

Thanks for this!  It fixes the issue at hand as far as I can tell.

I'd like to make a few general comments while you are learning the workflow of making changes in Multipass.

I see a number of changes that aren't really related to the fix itself- we tend to call these "drive by" changes and as reviewers, it makes it more difficult to tell what is fixing the actual issue vs. things you are just changing.  For example, changes in variable names, variable types, return types, and function names to name a few.

If a PR is fixing a bug, the PR should be focused on that.  If you want to propose changes to those types of things I mentioned previously, a separate PR is greatly appreciated with a description saying this is for renaming variables, changing types, etc.

That said, if it's a one or two line "drive by" fix in a separate commit in the same PR, we are usually fine with that and it doesn't add a bunch of extra lines in the diff. 

This way, it's clear to the reviewer what the intent of the PR is for.  I hope this makes sense.

For this PR, I prefer you revert the name changes back to what they were originally.  I don't mind you creating a follow up with the changes and at that point, we can discuss as a team if we would like those changes or a subset of the changes.

Again, thank you for the fix and putting this out there :slightly_smiling_face:

2023-03-10 09:37 UTC, georgeliao commented
@townsend2010 
I see, thanks for letting me know. I will revert things back to bug-fix changes only.

2023-03-10 11:53 UTC, georgeliao commented
Hi @townsend2010 

The requested changes have been done. The diff now is much smaller and purely focus on the bug fix.

2023-03-10 20:15 UTC, townsend2010 approved these changes
Hey @georgeliao,

This looks great!  One little niggle inline below, but I certainly won't block on it.  I'm approving and you can decide if you want to change it.

2023-03-10 20:15 UTC, townsend2010 commented on src/daemon/daemon.cpp
> +    const std::string blueprint_name = config->blueprint_provider->name_from_blueprint(request->image());
I'd prefer `const auto` here to follow the form of using `auto` where we can.

2023-03-10 20:15 UTC, townsend2010 commented
bors delegate

2023-03-10 20:17 UTC, townsend2010 commented
bors delegate+

2023-03-13 10:10 UTC, georgeliao commented
bors r+

2023-03-13 13:12 UTC, merged