[snapshots] Fail preemptively before prompting user
canonical/multipass pull request #3121
Opened 2023-06-13 05:52 UTC by sharder996

2023-07-10 21:44 UTC, ricab reviewed
Thanks @sharder996, this is getting there. Only a few rough edges left.

2023-07-10 21:44 UTC, ricab commented on src/daemon/daemon.cpp
> +            RestoreReply reply{};
This shadows the other `reply` var.

2023-07-10 21:44 UTC, ricab commented on src/daemon/daemon.cpp
> +            auto snapshot = vm_ptr->get_snapshot(request->snapshot());
You don't need this snapshot variable anywhere.

```suggestion
            vm_ptr->get_snapshot(request->snapshot());
```

2023-07-10 21:44 UTC, ricab commented on src/client/cli/cmd/restore.cpp
> +            RestoreRequest request;
Another shadow, this time for the field with the same name.

2023-07-10 21:44 UTC, ricab commented on src/client/cli/cmd/restore.cpp
> +                request.set_destructive(confirm_destruction(reply.instance()));
If you rename the local request, you can get the instance from `this`, e.g.:

```cpp
                repeat_request.set_destructive(confirm_destruction(request.instance()));
```

2023-07-10 21:44 UTC, ricab commented on src/rpc/multipass.proto
> +    string instance = 3;
I don't think you need this. See comment in restore.cpp.

2023-07-10 21:44 UTC, ricab commented on src/client/cli/cmd/restore.cpp
> -                "<instance>.<spanshot>.\n";
heh

2023-07-11 10:48 UTC, ricab reviewed
Thank you for addressing all of that so quickly @sharder996! One thing left to verify.

2023-07-11 10:48 UTC, ricab commented on src/daemon/daemon.cpp
> +        vm_ptr->get_snapshot(request->snapshot());
You removed the exception handing? I thought `NOT_FOUND` was appropriate. You can also place it together with the other catch at the end of the function. I would also add a comment to clarify why this is here.

2023-07-11 10:48 UTC, ricab commented on src/client/cli/cmd/restore.cpp
> +                client_response.set_destructive(confirm_destruction(this->request.instance()));
I don't think you need `this->` now that the names don't collide. But fine.

2023-07-12 10:45 UTC, ricab requested changes
Hey @sharder996, I was going to say only conflicts missing, but I just realized `multipass restore` now hangs.

2023-07-12 15:13 UTC, sharder996 commented
@ricab Are you sure you had the most recent changes? I noticed the command hanging as well, but had fixed it. Let me know if its still an issue for you, though.

2023-07-12 18:25 UTC, ricab approved these changes
Yeah, that's it! The snap is working for me now :slightly_smiling_face:

2023-07-12 18:25 UTC, merged