Desktop gui
canonical/multipass pull request #3282
Opened 2023-11-03 10:28 UTC by andrei-toterman

2024-03-28 13:28 UTC, townsend2010 requested changes
Hey @andrei-toterman!

Again, fantastic work here!  I'm submitting this review as-is because I pushed some changes for the Snap package and it seems I can't view some of my saved comments.  I will follow up with more comments as necessary.

2024-03-28 14:40 UTC, townsend2010 commented
Hey @andrei-toterman,

I think since the original GUI was removed, we can go back to using `gui` again for directories, etc. instead of `desktop-gui`.

Also, I'm still thinking about the name of this, both the executable and the app itself.  For the time being, let's rename it back to `multipass.gui` to be consistent with how the original GUI was named.  I'm still considering calling the app itself "Multipass Manager" and the executable `multipass-manager`, but I'd like to get some broad feedback about that.  To me, "Multipass" is the all encompassing product and calling the app that seems a bit...off.

2024-03-28 14:45 UTC, townsend2010 commented
I have also made quite a few changes to the snap package to trim it down.  It went from ~82MB down to ~64MB.  There is still some room for improvement, but I think this is sufficient for now.

2024-03-28 14:49 UTC, townsend2010 commented on snap/snapcraft.yaml
> +    - PKG_CONFIG_PATH: ""
I am unsure why these are here.  I see @luis4a0 added these.  Could you please explain @luis4a0?  Thanks!

2024-03-28 14:52 UTC, townsend2010 commented on snap/snapcraft.yaml
> +      /root/parts/desktop-gui/build/build/linux/x64/release/bundle: bin/
I'm not a real fan of **all** of the parts of the GUI bundle being dumped into `bin/`.  It's ok for now, but we should do better in another PR.

2024-03-28 16:48 UTC, townsend2010 commented
A UI "issue" I've found is that when you are in the list of instances and select one or more instances and then do an action such as start, stop, etc., the selections stay active and must be de-selected even after the action completes.  I think that once the action is complete, the instances should automatically be de-selected.  @vikorama, what do you think?

2024-03-28 17:32 UTC, vikorama commented
> A UI "issue" I've found is that when you are in the list of instances and select one or more instances and then do an action such as start, stop, etc., the selections stay active and must be de-selected even after the action completes. I think that once the action is complete, the instances should automatically be de-selected. @vikorama, what do you think?

Very good catch @townsend2010! I think the instance selection should stay selected as long as the user stays on the 'All instances' page. For example a flow like this: I select 5 running instances, pause them to free up recourses, do what I need to do in other apps, get back to Multipass and run the selected instances again.

I think that the selection should get de-selected when:
- a user opens up an individual instance page 
- goes to the Catalogue/Help/Settings
- searches for something on the 'All instances' page or removes a search query -> **already happening in the current package on Mac.**
- switches 'show running only' on or off ->  **already happening in the current package on Mac.** (this behaviour is arguable from the UX POV, but since it's already there, let's keep it for now)

What do you think?

2024-03-28 18:05 UTC, townsend2010 commented
Hey @vikorama!

I think what you propose makes perfect sense!  Thank you for your input!

2024-04-02 11:43 UTC, andrei-toterman commented on include/multipass/dart_ffi.h
Indeed it is possible! I will change it. Thanks for pointing it out!

2024-04-02 11:54 UTC, andrei-toterman commented on src/client/desktop_gui/ffi/dart_ffi.cpp
Hmm, I tried it and IMO now it looks a little weird, so I'd like your opinion. If I wrap everything in a block, then everything gets indented in that block according to our clang-format file. For the header file that is fine, since it's all function declarations. But for the function implementations, now their entire body is indented and IMO that makes it harder to read. What if we didn't indent stuff in `extern` blocks, just like we don't indent it in anonymous namespaces? We could add `IndentExternBlock: NoIndent` to the clang-format file.

2024-04-02 12:40 UTC, townsend2010 commented on src/client/desktop_gui/ffi/dart_ffi.cpp
Yeah, I would prefer the implementations not be indented, so yeah, add that directive to the clang-format file.  Thanks!

2024-04-02 12:45 UTC, andrei-toterman commented on src/simplestreams/simple_streams_manifest.cpp
> +    const QString& host_url)
Looks like that's the case. My bad, I will remove it!

2024-04-02 15:19 UTC, vikorama commented
@andrei-toterman A minor UI thing that we might want to fix is the placement of the context switcher (Shells vs Details). When designing, I wanted to place it next to the name of a VM, as it switches context for that particular instance. In the current package it stays next to stats and actions.

Here's what I propose. Let me know what you think. 
![Context switcher for this cycle](https://github.com/canonical/multipass/assets/129760288/6a5071f9-e5f6-4f06-b6d1-d83ec5b446d7)


In the future cycles we can look into making this top bar more responsive. Quick example below (just for context, not for implementation in this cycle):
![Context switcher wide](https://github.com/canonical/multipass/assets/129760288/79c115ef-f1b7-4a09-928f-1dcc34d39c23)
![Context switcher (1)](https://github.com/canonical/multipass/assets/129760288/94b5abd5-bd5c-4c5e-8131-317d0c973f0a)

2024-04-11 12:46 UTC, andrei-toterman commented on src/client/desktop_gui/ffi/dart_ffi.cpp
Something's strange here. So, I added that directive to the clang-format file. And locally it formats it as we'd like. But in CI it fails the lint step saying that it should be like this:
```cpp
extern "C" {
```
instead of how we'd like it
```cpp
extern "C"
{
```
Could it be because of a different version of clang-format maybe? Any other idea?

2024-04-16 20:25 UTC, townsend2010 commented on src/client/desktop_gui/ffi/dart_ffi.cpp
As discussed, let's just add `// clang-format off` and `// clang-format off` for the necessary parts to get it to look like we want it to :slightly_smiling_face:

2024-04-17 07:35 UTC, vikorama commented
@andrei-toterman Just looked at the new package, and fonts are looking great on Mac. 

One thing that didn't work for me:

- Deletion action is not purge (not sure if that commit went through), and all deleted instances are still in the list. When it's changed to purge, as discussed, let's also add this confirmation message: 
![Deletion confirmation (1)](https://github.com/canonical/multipass/assets/129760288/7556d8b7-bb53-47c7-8052-c26c1fc605d3)

One bug that might be related:
- I deleted an instance in GUI, successfully restored in in CLI, tried to start it again in GUI and then in CLI, and got this error
<img width="529" alt="image" src="https://github.com/canonical/multipass/assets/129760288/29f3ee06-aac1-49a7-8d94-6f8d10ff2666">



Things of lower priority (in my POV) that we touched upon:

- Tray menu: remove toggle window option on Mac, move primary to the list of all instances, add Open in Multipass option:
![Menu bar extras (2)](https://github.com/canonical/multipass/assets/129760288/a1cc81b5-511f-4cd2-9c64-6a4adbda40e2)

- When an instance running, it'd be nice to show this on hover for Configure:
![image (10)](https://github.com/canonical/multipass/assets/129760288/9b5b7417-0fbe-4d11-bcb6-54e1cc0ba684)

- As discussed [here](https://github.com/canonical/multipass/pull/3282#issuecomment-2032347043), would be nice to move the context switcher closer to the name of an instance:
![318842486-6a5071f9-e5f6-4f06-b6d1-d83ec5b446d7](https://github.com/canonical/multipass/assets/129760288/267b7c52-6312-4bc0-b8ad-72f8564a0d07)

2024-04-17 14:32 UTC, andrei-toterman commented
Hey, @vikorama! Thanks for the feedback! Indeed, most of the changes that you mentioned are not in the latest package. They are implemented, but due to various CI shenanigans, we couldn't obtain the packages with those changes. Hopefully they will be ready today.

2024-04-19 11:59 UTC, vikorama commented
@andrei-toterman As discussed, let's keep the context switcher as is for now. I agree that it's better to avoid it jumping around due to different name lengths. We might need to improve the visual design of the top panel in the future anyways, and it'd be easier to do it when we collect feedback after the first launch.

2024-04-19 12:53 UTC, townsend2010 approved these changes
Ok, this looks great in it's current form.  Let's get it in!!! :rocket:

2024-04-19 12:57 UTC, merged