Support Mantic compilers
canonical/multipass pull request #3285
Opened 2023-11-06 12:56 UTC by luis4a0

This fixes compilation with gcc-13 and clang-16.

2023-11-06 12:57 UTC, luis4a0 commented
Still having issues with the `fmt` lib with gcc-13.

2023-11-06 13:14 UTC, luis4a0 commented
Done.

2023-11-06 13:29 UTC, luis4a0 commented
Tested it also works with clang-17.

2023-11-15 19:28 UTC, townsend2010 requested changes
Seems fine overall, but I have one inline comment and a general question.  Why the need to add those escaped quotes in some of the strings?

2023-11-15 19:28 UTC, townsend2010 commented on 3rd-party/fmt
It looks like this is an update to the `fmt` submodule.  Please update the `3rd-party/submodule_info.md` file to reflect this?

2023-11-15 19:33 UTC, luis4a0 commented
Hey @townsend2010, thanks! I added those escape chars because, for some change in `fmt`, some strings which were outputted with double quotes don't have double quotes now. I wanted the output to be the same as before the change in `fmt`.

2023-11-16 16:52 UTC, luis4a0 commented on 3rd-party/fmt
Done. Switched to version 10.1.1 (the last stable) and reflected it in `submodule_info.md`.

2023-11-16 16:54 UTC, luis4a0 commented
Hey @townsend2010! The default formatting of `std::filesystem::path` changed in the last version of `fmtlib`. It used to quote the paths, and now it defaults to not quoting them. Thus I forced quoting where needed, so the tests are not affected by the change.

2023-11-21 14:40 UTC, townsend2010 approved these changes
Ok, LGTM, thanks!

2023-11-21 14:44 UTC, merged