Catch timeout on commands at boot
canonical/multipass pull request #3360
Opened 2024-01-08 20:19 UTC by luis4a0

Some executions can give a timeout for several reasons, but does not necessarily mean there was an error. However, the daemon used to fail on timeouts as it failed in severe cases like not being able to create a SSH connection. This PR makes the daemon catch the timeout exception, avoiding an error be shown to the user.

2024-01-10 20:31 UTC, townsend2010 requested changes
Hey @luis4a0!

Thanks for this!  I have a few comments below that I think need to be addressed.

2024-01-10 20:31 UTC, townsend2010 commented on src/daemon/daemon.cpp
> +        catch (const ExitlessSSHProcessException&) // Timeout does not mean there is a configuration error.
Why not just use the string returned in `what()` here and not have to capture the current command above?

2024-01-10 20:31 UTC, townsend2010 commented on src/daemon/daemon.cpp
> +            add_fmt_to(warnings, "Timeout executing command \"{}\" in instance {}.\n", *current_command, name);
Not sure if this really needs to be communicated back to the client.  I think logging the warning would be better.

2024-01-10 21:32 UTC, luis4a0 commented
Thanks for the review @townsend2010! I addressed your two points, so this is ready for a new round.

2024-01-11 13:38 UTC, townsend2010 approved these changes
Hey @luis4a0!

Looks much better now, thanks!  :+1:

2024-01-12 15:31 UTC, merged