Fix get local.instance.bridged
canonical/multipass pull request #3513
Opened 2024-04-26 14:03 UTC by luis4a0

The answer was wrong in some backends. This PR uses a more reliable mechanism, inspecting the contents of the platform networks data structure.

Fixes #3489.

2024-05-02 23:05 UTC, ricab requested changes
Hey @luis4a0, thanks for this PR. I think the idea of replacing the bridge name with a bridge member check is what we need. However, I am afraid I don't follow the new logic in `is_bridged`.

I think the idea is just (in pseudocode):

```cpp
alt_net = is_bridge(br_interface) ? nullopt : find_bridge_with(br_interface);
return std::any_of(spec.extra_interfaces.cbegin(),
                   spec.extra_interfaces.cend(),
                   [&br_interface, &alt_net](const auto& network) -> bool {
                       return network.id == br_interface || network.id == alt_net;
                   }); // this is there already
```

Regarding backends (or backend/platform combinations) where no bridge is necessary to connect the instance to the desired interface... Suppose that a user sets up a bridge (say `custom-bridge`) linked to the interface `some-net`. And suppose that they `multipass launch --network custom-bridge`. I don't think it is wrong to say that the resulting instance is bridged with `some-net`, even if the backend is VirtualBox and the bridge is unnecessary. I think it is actually more correct to say it is bridged. 

IOW, the logic above should be mostly independent from backends. The exception I see is the bridge type (bridge vs switch).

As discussed, I ignored tests for now.

2024-05-09 09:58 UTC, townsend2010 reviewed
Hey @luis4a0,

Why is there anything qemu related, particularly on Linux, in this PR?  Shouldn't this be done in #3463 once this PR is in?

2024-05-09 11:30 UTC, luis4a0 commented
Hey @townsend2010!

> Why is there anything qemu related, particularly on Linux, in this PR? Shouldn't this be done in https://github.com/canonical/multipass/pull/3463 once this PR is in?

On one hand, moving to platform detail is needed because the code will be different for macOS QEMU. On the other hand, you are right in the sense that the particular function implementation will be needed after bridging is implemented in Linux QEMU. I can make the detail function on Linux throw, and then in the other PR introduce the code again.

2024-05-09 13:09 UTC, luis4a0 commented
Hey @townsend2010, @ricab! I addressed all the concerns above, and added some tests. This is ready for review now.

2024-05-09 13:09 UTC, luis4a0 commented on src/daemon/daemon.cpp
> +    const auto& br_it = config->factory->find_bridge_with(host_nets, br_interface, "bridge");
Right, fixed.

2024-05-09 13:10 UTC, luis4a0 commented on src/daemon/daemon.cpp
> +    }
Yeah, you're right. I removed this and modified the last one in the function.

2024-05-31 11:05 UTC, ricab requested changes
This PR moves `find_bridge_with` to backends, but the code therein is essentially independent of backends. We'll need a different approach.

2024-05-31 11:05 UTC, closed without merging