add snapcraft 24.04 aliases
canonical/multipass pull request #3613
Opened 2024-07-31 11:33 UTC by andrei-toterman

2024-07-31 11:38 UTC, ricab requested changes

2024-07-31 11:38 UTC, ricab commented on src/platform/platform_shared.h
> +                                                                  "24.04"
missing a comma ;)

2024-07-31 11:40 UTC, andrei-toterman commented on src/platform/platform_shared.h
> +                                                                  "24.04"
oopsie

2024-07-31 11:45 UTC, ricab reviewed
Looks good, thanks. I'll just want to give it a spin on a couple of platforms before merging.

2024-08-02 21:26 UTC, ricab approved these changes
Worked smoothly, thanks again.

2024-08-02 22:48 UTC, merged