1[3rd part fmt] update fmt submodule from 10.1.1 to 11.0.2 and applie…
canonical/multipass pull request #3616
Opened 2024-08-01 12:49 UTC by georgeliao

…d corresponding code changes.

2024-09-24 18:19 UTC, Sploder12 reviewed
LGTM so far, just a couple links that should be updated. Notify me when gRPC is ready! :)

2024-10-01 13:50 UTC, georgeliao commented on 3rd-party/libssh/CMakeLists.txt
> +  libssh_VERSION "${libssh_VERSION}")
This change is due to the regex match failure stems from the change in the internal CMakeLists.txt change of libssh, the line 
`project(libssh VERSION 0.11.1 LANGUAGES C CXX)` is appended with CXX.

2024-10-01 13:51 UTC, georgeliao commented on 3rd-party/submodule_info.md
> +Version: 0.11.1 (+[our patches](https://github.com/canonical/libssh/compare/libssh-0.11.1...multipass)) |
Using `multipass` branch name as opposed to commit hash to prevent adaptive change in the future.

2024-10-01 14:00 UTC, georgeliao commented
Hi @Sploder12 
The part1 of 3rd party library update is ready for review. 

I did a final scan on the latest version of the packages, it turned out that libssh can be upgraded further to 0.11.1 instead of 0.10.6. So the corresponding cherry-pick and push were done. Please perform a careful check on the new patches, meaning compare the patches with the ones on the 0.10.5 and see if it makes sense. You can find it either via `submodule_info.md` patch link or jump to the libssh repo by yourself. Please do the very same thing to yaml-cpp as well, if you have done that already, just simply let me know it looks good to you.

2024-10-01 16:21 UTC, Sploder12 requested changes
Mostly good. Tests pass and didn't notice any issues when running! Just some issues with edge cases in libssh changes.

2024-10-01 16:21 UTC, Sploder12 commented on 3rd-party/libssh/libssh
in file `src/sftpserver.c`

lines `674-676`: if `realloc` fails then `sftp->total_allocated_handles` is still as if the `realloc` succeeded, this could lead to out-of-bounds issues later on in the program. 

line `708`: potential off by one error, the check should probably be `>=`

2024-10-02 12:49 UTC, georgeliao commented
> in file src/sftpserver.c
> 
> lines 674-676: if realloc fails then sftp->total_allocated_handles is still as if the realloc succeeded, this could lead to out-of-bounds issues later on in the program.

```
  if (i == sftp->total_allocated_handles) {
    uint32_t old_size = sftp->total_allocated_handles;
    sftp->total_allocated_handles += SFTP_HANDLES_CHUNK_SZ;

    void **tmp = realloc(sftp->handles, sftp->total_allocated_handles * sizeof(void *));
    if (tmp == NULL)
        return NULL; /* no handle available */

    sftp->handles = tmp;
    memset(sftp->handles + old_size, '\0', SFTP_HANDLES_CHUNK_SZ * sizeof(void *));
  }
```

Indeed, `sftp->total_allocated_handles` should be incremented only if realloc succeeds, what do you think of the code snippet below? 

```
  if (i == sftp->total_allocated_handles) {
    uint32_t temp_new_size = sftp->total_allocated_handles + SFTP_HANDLES_CHUNK_SZ;

    void **tmp = realloc(sftp->handles, temp_new_size * sizeof(void *));
    if (tmp == NULL)
        return NULL; /* no handle available */

    sftp->handles = tmp;
    uint32_t old_size = sftp->total_allocated_handles;
    sftp->total_allocated_handles = temp_new_size;
    memset(sftp->handles + old_size, '\0', SFTP_HANDLES_CHUNK_SZ * sizeof(void *));
  }
```

2024-10-02 12:58 UTC, Sploder12 commented
> > line 708: potential off by one error, the check should probably be >=
> 
> Not sure I get this one, did you mean `val` is 0-index based so `val == sftp->total_allocated_handles` is already an invalid condition?
> 
> ```
>     memcpy(&val, ssh_string_data(handle), sizeof(uint32_t));
> 
>     if (val > sftp->total_allocated_handles) {
>       return NULL;
>     }
> ```

Yeah, if `val == sftp->total_allocated_handles` then there is an out of bounds read afterwards.

2024-10-02 13:02 UTC, Sploder12 commented
> ```
>   if (i == sftp->total_allocated_handles) {
>     uint32_t old_size = sftp->total_allocated_handles;
>     sftp->total_allocated_handles += SFTP_HANDLES_CHUNK_SZ;
> 
>     void **tmp = realloc(sftp->handles, sftp->total_allocated_handles * sizeof(void *));
>     if (tmp == NULL)
>         return NULL; /* no handle available */
> 
>     sftp->handles = tmp;
>     memset(sftp->handles + old_size, '\0', SFTP_HANDLES_CHUNK_SZ * sizeof(void *));
>   }
> ```
> 
> Indeed, `sftp->total_allocated_handles` should be incremented only if realloc succeeds, what do you think of the proposed code snippet below?
> 
> ```
>   if (i == sftp->total_allocated_handles) {
>     uint32_t temp_new_size = sftp->total_allocated_handles + SFTP_HANDLES_CHUNK_SZ;
> 
>     void **tmp = realloc(sftp->handles, temp_new_size * sizeof(void *));
>     if (tmp == NULL)
>         return NULL; /* no handle available */
> 
>     sftp->handles = tmp;
>     uint32_t old_size = sftp->total_allocated_handles;
>     sftp->total_allocated_handles = temp_new_size;
>     memset(sftp->handles + old_size, '\0', SFTP_HANDLES_CHUNK_SZ * sizeof(void *));
>   }
> ```
The proposed code looks good!

2024-10-02 13:07 UTC, georgeliao commented
@Sploder12 
Another thing is that the windows build has been failing on `ssh` lib compilation since we upgraded to 1.10.6 from 1.10.5, the private part has a small change to fix that. See the intro comment for the link to the private side.

2024-10-02 13:10 UTC, georgeliao commented
> Yeah, if val == sftp->total_allocated_handles then there is an out of bounds read afterwards.

Then we are also fixing the `libssh` original code as opposed to fixing out patches. Not sure if we should do that. 

> The proposed code looks good!

This one is fixing the legacy patches as opposed to this particular rebase. So maybe this can be done.

2024-10-02 13:45 UTC, georgeliao commented
@Sploder12 

> The proposed code looks good!

This is added to libssh repo. Please have another check. The other change will deviate from the original code of libssh and it adds complexity to the patches even though it might be a corner case bug. So I am inclined to leave it. What do you think?

2024-10-02 13:55 UTC, Sploder12 commented
> This is added to libssh repo. Please have another check. The other change will deviate from the original code of libssh and it adds complexity to the patches even though it might be a corner case bug. So I am inclined to leave it. What do you think?

Looks good! It's not a big bug, and I doubt it's possible under normal execution, so I think leaving it is fine. Sorry, GitHub doesn't really make submodule changes clear.

2024-10-02 13:56 UTC, Sploder12 submitted a review, later dismissed

2024-10-02 15:56 UTC, georgeliao commented
@Sploder12 
The latest commit cherry-pick was redone, so now it only grafts the commit. Feel free to make another PR to adapt the format and add the `if` block code we have proposed in a different PR. 

Once the build is finished, feel free to merge.

2024-10-02 17:19 UTC, Sploder12 approved these changes
LGTM!

2024-10-03 13:30 UTC, ricab commented
This won't pass on the merge queue without the private side, need to merge manually.

2024-10-03 13:49 UTC, merged