Mount redesign
canonical/multipass pull request #3698
Opened 2024-09-24 21:00 UTC by andrei-toterman

This PR implements the redesign of the mounting interface, as well as some cosmetic changes to the pages that use the mounting interface, namely the launch panel and the individual instance page.

See https://warthogs.atlassian.net/browse/MULTI-894 and https://warthogs.atlassian.net/browse/MULTI-895 for the details of the changes.

There was also some refactoring of adjacent code that is not necessarily mount-related (e.g. splitting some files into multiple files), so that the modification and addition of the mount code is easier

2024-10-08 22:31 UTC, levkropp requested changes
Well done!! The mount section looks good and is intuitive to use. I also liked how you turned ConfirmationDialog into a reusable widget 😃

2024-10-08 22:31 UTC, levkropp commented on src/client/gui/lib/catalogue/launch_form.dart
> +      helper: 'Namess cannot be changed one an instance is created',
Typo in "Names" and "once"

2024-10-11 19:09 UTC, levkropp submitted a review, later dismissed

2024-10-22 10:11 UTC, ricab requested changes
Hi Andrei,

Thanks, looking very nice. Most of what I tried worked as it should, but I did find a few things to look into: 

- Default mount path points to the inside of the snap, whereas design specifies it should start at the home directory
![Screenshot from 2024-10-22 11-29-49](https://github.com/user-attachments/assets/700a3e45-03e0-4914-8317-486cbf6235b0)
- Placeholder/square char in the dialogue to delete a mount 
![Screenshot from 2024-10-22 11-35-04](https://github.com/user-attachments/assets/d4b0fbf3-bebd-4e19-a6f0-1dd402b121a7)
- After deleting the last couple of mounts, the "cancel" button lingers and "add mount" is no longer present - it should perhaps go back to the initial state, with "add mount" on the right
![Screenshot from 2024-10-22 11-41-00](https://github.com/user-attachments/assets/b6930d0b-64ec-433b-ad1d-073a84b9b677)
- very long paths are not "truncated in the middle" when in saved state 
![Screenshot from 2024-10-22 12-00-18](https://github.com/user-attachments/assets/affa0f65-f6a1-488e-af1f-6dbe402620df)

To discuss with Design:
- Save being disabled when new mount empty - not sure what disabled state means
- file chooser not opening in Home - opening in recent instead
    - if a path is already filled in, should it start from there?
- when I delete a mount, leaving others behind, it is a little weird to see a cancel button, since the action cannot be reverted any longer. Should it say "Save" instead? But save without cancel is weird. Should it just go back to "saved mount state", as when adding a mount? Or maybe the text should be changed to "Done"... On the same topic, if I add a mount, then select "cancel", the mount remains.

2024-10-22 11:36 UTC, andrei-toterman commented
Regarding the 3rd point with the 'add mount' button not being present, I don't think it should appear on the right, but on the left where it appears when there are mounts present. 'Add mount' is on the right when we are not in the 'Configure' mode of the form.

And I agree that 'Cancel' is a mid misleading since it doesn't really cancel stuff. What about just 'Close' for now?

2024-10-23 10:12 UTC, ricab commented
Only that last permissions thing missing, otherwise looking good.

2024-10-23 16:09 UTC, merged