Remove chmod and duplicated permissions functions
canonical/multipass pull request #3782
Opened 2024-11-18 19:41 UTC by Sploder12

This PR removes `chmod` from `Platform.h` as well as functions that are similar in `file_ops.h`. They have all been changed to use `MP_PLATFORM.set_permissions`. This should not change behavior on Unix systems. On Windows this changes the behavior to modify ACLs as well as DOS permissions instead of just DOS permissions.

MULTI-1420

2025-01-14 00:02 UTC, sharder996 requested changes
Looks good! Thanks for cleaning this up and using the `std::filesystem`! Just a few things to clean up and it should be good.

2025-01-14 18:20 UTC, Sploder12 commented on src/platform/platform_unix.cpp
> +    std::filesystem::permissions(path, permissions, ec);
changing the signature wouldn't work since Windows can fail for reasons that don't create or map to an `error_code`. But logging sounds like a good idea!

2025-01-17 20:37 UTC, Sploder12 commented on src/utils/utils.cpp
> +    if (permissions != std::filesystem::perms::none)
The enum is not implicitly convertible to `bool`, I prefer this over an explicit cast to `bool`

2025-01-17 21:15 UTC, Sploder12 commented on tests/linux/test_platform_linux.cpp
> +        .WillOnce(Return(std::filesystem::perms::owner_read | std::filesystem::perms::owner_write));
`Return()` won't work since `get_permissions` doesn't return `void`, I chose owner read write since that's how the test was originally with QPermissions. But any std perms should be fine.

2025-01-21 10:31 UTC, georgeliao reviewed
@Sploder12 
Excellent job, it is nice to have a uniform std way of setting and getting file permissions. I only have some minor comments.

2025-01-21 10:31 UTC, georgeliao commented on tests/linux/test_platform_linux.cpp
> +                                                     mp::AliasDefinition{"instance", "other_command", "map"}));
You can just use `MP_PLATFORM.Platform::create_alias_script` which is more similar with the original code. With `Platform::` qualified name, virtual dispatch and the object type is bypassed anyway. So the base class reference or derived class object calls are the same.

2025-01-21 10:31 UTC, georgeliao commented on src/utils/utils.cpp
> +        MP_PLATFORM.set_permissions(dir_path.toStdU16String(), permissions);
Same wandering as [here](https://github.com/canonical/multipass/pull/3846#discussion_r1922240626).

2025-01-23 14:00 UTC, georgeliao approved these changes

2025-01-24 14:07 UTC, sharder996 submitted a review, later dismissed

2025-01-24 16:02 UTC, georgeliao commented
For this PR, we also need to manually merge this because of the private side. I do not think we have to permission. @ricab may have to step in.

2025-01-24 19:57 UTC, sharder996 approved these changes

2025-01-27 12:46 UTC, ricab commented
Merging manually since this needs the other side.

2025-01-27 12:46 UTC, merged